###
library(data.table)
ep<-fread("household_power_consumption.txt",sep=";",header=T,stringsAsFactor=FALSE,colClasses="character")     
ep_plot<-subset(ep,Date=="1/2/2007" | Date=="2/2/2007")
dt<-strptime(paste(ep_plot$Date,ep_plot$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png",width=480,height=480)
sub2<-as.numeric(ep_plot$Sub_metering_2)
sub3<-as.numeric(ep_plot$Sub_metering_3)
sub1<-as.numeric(ep_plot$Sub_metering_1)
plot(dt,sub1, type='l',ylab="Energy sub metering",xlab="")
lines(dt,sub2,type="l",col="red")
lines(dt,sub3,type="l",col="blue")
legend("topright",c("Sub-metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=3,col=c("black","red","blue"))
dev.off()